# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title: St. Catherines Catholic Primary School Littlehampton
description: Parent Teacher and Friends Association

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
